create schema if not exists shipping_management;

create table if not exists shipping_management.t_region
(
    c_region_id int primary key generated by default as identity,
    c_name      text not null check ( length(trim(c_name)) > 0 )
);

create table if not exists shipping_management.t_settlement
(
    c_settlement_id int primary key generated by default as identity,
    c_region_id     int  not null,
    c_name          text not null check ( length(trim(c_name)) > 0 ),
    constraint fk_city_region foreign key (c_region_id)
        references shipping_management.t_region (c_region_id) on delete cascade
);

create table if not exists shipping_management.t_address
(
    c_address_id    bigint primary key generated by default as identity,
    c_settlement_id int not null,
    c_street        text,
    c_building      text,
    c_type          text check ( c_type in ('СЦ', 'пункт выдачи', 'склад') ),
    constraint fk_address_city foreign key (c_settlement_id)
        references shipping_management.t_settlement (c_settlement_id) on delete cascade
);

create table if not exists shipping_management.t_client
(
    c_account_id             bigint primary key generated by default as identity,
    c_fio                    text not null check ( length(trim(c_fio)) > 0 ),
    c_passport_series_number text not null check ( length(trim(c_passport_series_number)) = 10),
    c_phone_number           text not null check ( length(trim(c_phone_number)) <= 15 ),
    c_status                 text not null check ( c_status in ('клиент', 'партнёр') )
);

create table if not exists shipping_management.t_shipping_order
(
    c_order_id         bigint primary key generated by default as identity,
    c_sender_id        bigint      not null,
    c_consumer_id      bigint      not null,
    c_shipment_address bigint      not null,
    c_delivery_address bigint      not null,
    c_price            decimal     not null,
    c_creation_date    timestamptz not null,
    c_completion_date  timestamptz,
    c_is_completed     bool        not null,
    c_priority         text        not null check ( c_priority in ('стандарт', 'быстро', 'срочная доставка') ), -- todo
    constraint fk_order_sender foreign key (c_sender_id)
        references shipping_management.t_client (c_account_id) on delete cascade,
    constraint fk_order_consumer foreign key (c_consumer_id)
        references shipping_management.t_client (c_account_id) on delete cascade,
    constraint fk_order_shipment_address foreign key (c_shipment_address)
        references shipping_management.t_address (c_address_id) on delete cascade,
    constraint fk_order_delivery_address foreign key (c_delivery_address)
        references shipping_management.t_address (c_address_id) on delete cascade
);

create table if not exists shipping_management.t_cargo_type
(
    c_cargo_type_id int primary key generated by default as identity,
    c_name          text not null
);

create table if not exists shipping_management.t_rate
(
    c_rate_id    bigint primary key generated by default as identity,
    c_name       text    not null,
    c_max_width  decimal not null,
    c_max_height decimal not null,
    c_max_length decimal not null,
    c_max_weight decimal not null,
    c_multiplier decimal not null
);

create table if not exists shipping_management.t_cargo
(
    c_cargo_id bigint primary key generated by default as identity,
    c_order_id bigint  not null,
    c_rate_id  bigint  not null,
    c_width    decimal not null,
    c_height   decimal not null,
    c_length   decimal not null,
    c_weight   decimal not null check ( c_weight between 0.1 and 500),
    c_type     int     not null,
    c_price    decimal not null,
    constraint fk_cargo_order foreign key (c_order_id)
        references shipping_management.t_shipping_order (c_order_id) on delete cascade,
    constraint fk_cargo_rate foreign key (c_rate_id)
        references shipping_management.t_rate (c_rate_id) on delete cascade,
    constraint fk_cargo_type foreign key (c_type)
        references shipping_management.t_cargo_type (c_cargo_type_id) on delete cascade
);

create table if not exists shipping_management.t_route
(
    c_route_id    bigint primary key generated by default as identity,
    c_start_point bigint  not null,
    c_end_point   bigint  not null,
    c_length      decimal not null,
    constraint fk_route_start_address foreign key (c_start_point)
        references shipping_management.t_address (c_address_id) on delete cascade,
    constraint fk_route_end_address foreign key (c_end_point)
        references shipping_management.t_address (c_address_id) on delete cascade
);

create table if not exists shipping_management.t_vehicle
(
    c_vehicle_number    text primary key check ( length(c_vehicle_number) between 8 and 9),
    c_carrying_capacity decimal not null,
    c_body_volume       decimal not null
);

create table if not exists shipping_management.t_allowed_cargo_types
(
    c_vehicle_number text not null,
    c_cargo_type_id  int  not null,
    constraint fk_allowed_cargo_types_vehicle foreign key (c_vehicle_number)
        references shipping_management.t_vehicle (c_vehicle_number) on delete cascade,
    constraint fk_allowed_cargo_types_cargo foreign key (c_cargo_type_id)
        references shipping_management.t_cargo_type (c_cargo_type_id) on delete cascade
);

create table if not exists shipping_management.t_driver
(
    c_account_id      bigint primary key generated by default as identity,
    c_fio             text not null check ( length(trim(c_fio)) > 0 ),
    c_phone_number    text not null check ( length(trim(c_phone_number)) < 15 ),
    c_job_start_date  date not null check ( c_job_start_date > '1900.01.01' ),
    c_status          text not null check ( c_status in ('свободен', 'в отпуске', 'в рейсе') ),
    c_current_address bigint,
    constraint fk_driver_current_address foreign key (c_current_address)
        references shipping_management.t_address (c_address_id) on delete cascade
);

create table if not exists shipping_management.t_driver_vehicle
(
    c_driver_id               bigint not null,
    c_vehicle_id              text   not null,
    c_exploitation_start_date date   not null,
    c_exploitation_end_date   date   not null,
    constraint fk_driver_vehicle_driver foreign key (c_driver_id)
        references shipping_management.t_driver (c_account_id) on delete cascade,
    constraint fk_driver_vehicle_vehicle foreign key (c_vehicle_id)
        references shipping_management.t_vehicle (c_vehicle_number) on delete cascade
);

create table if not exists shipping_management.t_history
(
    c_order_id       bigint      not null,
    c_date           timestamptz not null,
    c_route_id       bigint,
    c_status         text check ( c_status in ('оформлен', 'в пути', 'прибыл', 'готов к выдаче', 'получен') ),
    c_comment        text,
    c_driver_id      bigint      not null,
    c_vehicle_number text,
    constraint fk_history_order foreign key (c_order_id)
        references shipping_management.t_shipping_order (c_order_id) on delete cascade,
    constraint fk_history_route foreign key (c_route_id)
        references shipping_management.t_route (c_route_id) on delete cascade,
    constraint fk_history_driver foreign key (c_driver_id)
        references shipping_management.t_driver (c_account_id) on delete cascade,
    constraint fk_history_vehicle foreign key (c_vehicle_number)
        references shipping_management.t_vehicle (c_vehicle_number) on delete cascade
);

create table if not exists shipping_management.t_shipping_way
(
    c_shipping_way_id bigint primary key generated by default as identity,
    c_driver_id       bigint  not null,
    c_is_completed    boolean not null,
    constraint fk_shipping_way_driver foreign key (c_driver_id)
        references shipping_management.t_driver (c_account_id) on delete cascade
);

create table if not exists shipping_management.t_shipping_way_routes
(
    c_shipping_way_id bigint      not null,
    c_route_id        bigint      not null,
    c_status          text        not null check ( c_status in ('пройден', 'в пути', 'предстоит') ),
    c_start_date      timestamptz not null,
    c_end_date        timestamptz not null,
    constraint fk_shipping_way_routes_shipping_way foreign key (c_shipping_way_id)
        references shipping_management.t_shipping_way (c_shipping_way_id),
    constraint fk_shipping_way_routes_route foreign key (c_route_id)
        references shipping_management.t_route (c_route_id)
);

create table if not exists shipping_management.t_shipping_way_shipping_order
(
    c_shipping_way_id   bigint      not null,
    c_shipping_order_id bigint      not null,
    c_entry_date        timestamptz not null,
    c_out_date          timestamptz,
    constraint fk_shipping_way_shipping_order_shipping_way foreign key (c_shipping_way_id)
        references shipping_management.t_shipping_way (c_shipping_way_id) on delete cascade,
    constraint fk_shipping_way_shipping_order_shipping_order foreign key (c_shipping_order_id)
        references shipping_management.t_shipping_order (c_order_id) on delete cascade
);

create table if not exists shipping_management.t_report
(
    c_report_id       bigint primary key generated by default as identity,
    c_shipping_way_id bigint      not null,
    c_date            timestamptz not null,
    c_road_hours      int         not null,
    constraint fk_report_shipping_way foreign key (c_shipping_way_id)
        references shipping_management.t_shipping_way (c_shipping_way_id)
);

-- назначение тарифа на основе габаритов
create or replace function shipping_management.fn_assign_or_validate_rate()
    returns trigger as
$$
declare
    correct_rate_id bigint;
begin
    select c_rate_id
    into correct_rate_id
    from shipping_management.t_rate
    where new.c_width <= c_max_width
      and new.c_height <= c_max_height
      and new.c_length <= c_max_length
      and new.c_weight <= c_max_weight
    order by c_max_width + c_max_height + c_max_length + c_max_weight
    limit 1;

    if correct_rate_id is null then
        raise exception 'Не найден подходящий тариф для груза: ширина=%, длина=%, высота=%, вес=%',
            new.c_width, new.c_length, new.c_height, new.c_weight;
    end if;

    if new.c_rate_id is distinct from correct_rate_id then
        new.c_rate_id := correct_rate_id;
    end if;

    return new;
end;
$$ language plpgsql;

create trigger trg_validate_rate_before_update_cargo
    before update of c_width, c_height, c_length, c_weight, c_rate_id
        or insert
    on shipping_management.t_cargo
    for each row
execute function shipping_management.fn_assign_or_validate_rate();

-- Стоимость присваивается заказу на основе суммы стоимости всех грузов
create or replace function shipping_management.fn_assign_shipping_order_price()
    returns trigger as
$$
declare
    v_total_price decimal;
    v_order_id    bigint;
begin
    if tg_op = 'DELETE' then
        v_order_id := old.c_order_id;
    else
        v_order_id := new.c_order_id;
    end if;

    select coalesce(sum(c_price), 0)
    into v_total_price
    from shipping_management.t_cargo
    where c_order_id = v_order_id;

    update shipping_management.t_shipping_order
    set c_price = v_total_price
    where c_order_id = v_order_id;

    return null;
end;
$$ language plpgsql;

create trigger trg_assign_shipping_order_price
    after insert or update of c_price or delete
    on shipping_management.t_cargo
    for each row
execute function shipping_management.fn_assign_shipping_order_price();

-- Нельзя назначить заказ водителю, находящемуся в отпуске или в рейсе
create function shipping_management.fn_check_shipping_way_driver_availability()
    returns trigger as
$$
declare
    v_driver_status text;
begin
    select c_status
    into v_driver_status
    from shipping_management.t_driver
    where new.c_driver_id = c_account_id;

    if v_driver_status = 'в отпуске' or v_driver_status = 'в рейсе' then
        raise exception 'Нельзя назначить рейс водителю с статусом %', v_driver_status;
    end if;

    return new;
end;
$$ language plpgsql;

create trigger trg_check_shipping_way_driver_availability
    before insert
    on shipping_management.t_shipping_way
    for each row
execute function shipping_management.fn_check_shipping_way_driver_availability();

-- водитель может быть не более чем в 1 рейсе
create function shipping_management.fn_validate_shipping_ways_number()
    returns trigger as
$$
declare
    v_count_active int;
begin
    select count(*)
    into v_count_active
    from shipping_management.t_shipping_way
    where c_driver_id = new.c_driver_id
      AND c_is_completed = false;

    if v_count_active >= 1 then
        raise exception 'Водитель не может быть более чем в 1 рейсе одновременно';
    end if;

    return new;
end;
$$ language plpgsql;

create trigger trg_validate_shipping_ways_number
    before insert
    on shipping_management.t_shipping_way
    for each row
execute function shipping_management.fn_validate_shipping_ways_number();

-- ставим водителю статус в рейсе при назначении рейса
create or replace function shipping_management.fn_set_driver_status_to_in_trip()
    returns trigger as
$$
begin
    update shipping_management.t_driver
    set c_status = 'в рейсе'
    where c_account_id = new.c_driver_id;

    return new;
end;
$$ language plpgsql;

create trigger trg_set_driver_status_to_in_trip
    after insert
    on shipping_management.t_shipping_way
    for each row
    when (new.c_is_completed = false)
execute function shipping_management.fn_set_driver_status_to_in_trip();

-- при завершении рейса водитель становится свободен
create or replace function shipping_management.fn_set_driver_status_to_free_on_trip_completion()
    returns trigger as
$$
begin
    if old.c_is_completed = false and new.c_is_completed = true then
        update shipping_management.t_driver
        set c_status = 'свободен'
        where c_account_id = new.c_driver_id;
    end if;

    return new;
end;
$$ language plpgsql;

create trigger trg_set_driver_status_to_free_on_trip_completion
    after update of c_is_completed
    on shipping_management.t_shipping_way
    for each row
    when (old.c_is_completed = false and new.c_is_completed = true)
execute function shipping_management.fn_set_driver_status_to_free_on_trip_completion();

create or replace function shipping_management.fn_set_shipping_order_completion()
    returns trigger as
$$
begin
    update shipping_management.t_shipping_order
    set c_is_completed    = true,
        c_completion_date = new.c_date
    where c_order_id = new.c_order_id;

    return new;
end;
$$ language plpgsql;

create trigger trg_set_shipping_order_completion
    after insert
    on shipping_management.t_history
    for each row
execute function shipping_management.fn_set_shipping_order_completion();