create schema if not exists shipping_management;

create table if not exists shipping_management.t_client
(
    c_account_id             bigint primary key generated by default as identity,
    c_fio                    text not null check ( length(trim(c_fio)) > 0 ),
    c_passport_series_number text not null check ( length(trim(c_passport_series_number)) = 10), -- todo
    c_phone_number           text not null check ( length(trim(c_phone_number)) <= 15 ), -- todo
    c_status                 text not null check ( c_status in ('Клиент', 'Партнёр') )
);

create table if not exists shipping_management.t_shipping_order
(
    c_order_id         bigint primary key generated by default as identity,
    c_client_id        bigint      not null,
    c_driver_id        bigint      not null,
    c_rate_id          bigint      not null,
    c_shipment_address bigint      not null,
    c_delivery_address bigint      not null,
    c_price            decimal     not null,
    c_creation_date    timestamptz not null, -- <-------------------- денормализация
    c_is_completed     bool        not null, -- <-------------------- денормализация // todo
    constraint fk_order_client foreign key (c_client_id)
        references shipping_management.t_client (c_account_id) on delete cascade,
    constraint fk_order_driver foreign key (c_driver_id)
        references shipping_management.t_driver (c_account_id) on delete cascade,
    constraint fk_order_rate foreign key (c_rate_id)
        references shipping_management.t_rate (c_rate_id) on delete cascade,
    constraint fk_order_shipment_address foreign key (c_shipment_address)
        references shipping_management.t_address (c_address_id) on delete cascade,
    constraint fk_order_delivery_address foreign key (c_delivery_address)
        references shipping_management.t_address (c_address_id) on delete cascade
);

create table if not exists shipping_management.t_cargo
(
    c_cargo_id bigint primary key generated by default as identity,
    c_order_id bigint  not null,
    c_size     text    not null,
    c_weight   decimal not null check ( c_weight between 0.1 and 200),
    c_type     text check ( c_type in ('Письмо', 'Хрупкое', 'Животные', 'Крупногабаритное') ),
    constraint fk_cargo_order foreign key (c_order_id)
        references shipping_management.t_shipping_order (c_order_id) on delete cascade
);

create table if not exists shipping_management.t_route
(
    c_route_id    bigint primary key generated by default as identity,
    c_start_point bigint  not null,
    c_end_point   bigint  not null,
    c_length      decimal not null,
    constraint fk_route_start_address foreign key (c_start_point)
        references shipping_management.t_address (c_address_id) on delete cascade,
    constraint fk_route_end_address foreign key (c_end_point)
        references shipping_management.t_address (c_address_id) on delete cascade
);

create table if not exists shipping_management.t_vehicle
(
    c_vehicle_number    text primary key check ( length(c_vehicle_number) between 8 and 9),
    c_carrying_capacity decimal not null,
    c_body_volume       decimal not null
);

create table if not exists shipping_management.t_driver
(
    c_account_id     bigint primary key generated by default as identity,
    c_fio            text not null check ( length(trim(c_fio)) > 0 ),
    c_phone_number   text not null check ( length(trim(c_phone_number)) > 15 ),
    c_job_start_date date not null check ( c_job_start_date > '1900.01.01' )
);

create table if not exists shipping_management.t_address
(
    c_address_id bigint primary key generated by default as identity,
    c_city_id    int not null,
    c_street     text,
    c_building   text,
    c_type       text check ( c_type in ('СЦ', 'Пункт выдачи') ),
    constraint fk_address_city foreign key (c_city_id)
        references shipping_management.t_city (c_city_id) on delete cascade
);

create table if not exists shipping_management.t_rate
(
    c_rate_id    bigint primary key generated by default as identity,
    c_name       text    not null check ( c_name in
                                          ('Конверт', 'Короб XS', 'Короб S', 'Короб M', 'Короб L', 'Короб XL',
                                           'Чемодан',
                                           'Палетта') ),
    c_multiplier decimal not null
);

create table if not exists shipping_management.t_history
(
    c_order_id bigint      not null,
    c_date     timestamptz not null,
    c_route_id bigint,
    c_status   text check ( c_status in ('Оформлен', 'В пути', 'Прибыл', 'Готов к выдаче') ),
    c_comment  text,
    constraint fk_history_order foreign key (c_order_id)
        references shipping_management.t_shipping_order (c_order_id) on delete cascade,
    constraint fk_history_route foreign key (c_route_id)
        references shipping_management.t_route (c_route_id) on delete cascade
);

create table if not exists shipping_management.t_region
(
    c_region_id int primary key generated by default as identity,
    c_name      text not null check ( length(trim(c_name)) > 0 )
);

create table if not exists shipping_management.t_city
(
    c_city_id   int primary key generated by default as identity,
    c_region_id int  not null,
    c_name      text not null check ( length(trim(c_name)) > 0 ),
    constraint fk_city_region foreign key (c_region_id)
        references shipping_management.t_region (c_region_id) on delete cascade
);